######TESTING REPORT######

Date: Thu Sep  9 15:59:39 CDT 2021 

---UNITTEST---

test_dequip (tests.test_armor.ArmorTest) ... FAIL
test_details (tests.test_armor.ArmorTest) ... FAIL
test_equip (tests.test_armor.ArmorTest)
Testing that the equip function for success ... ok
test_export (tests.test_armor.ArmorTest) ... FAIL
test_init (tests.test_armor.ArmorTest) ... ok
test_printToFile (tests.test_armor.ArmorTest) ... ok
test_str (tests.test_armor.ArmorTest) ... ok
test_details (tests.test_equipment.EquipmentTest) ... ok
test_export (tests.test_equipment.EquipmentTest) ... ok
test_init (tests.test_equipment.EquipmentTest) ... ok
test_printToFile (tests.test_equipment.EquipmentTest) ... ok
test_str (tests.test_equipment.EquipmentTest) ... ok

======================================================================
FAIL: test_dequip (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/Jevin.Evans/Documents/CODE/Game/FUNCLG/tests/test_armor.py", line 193, in test_dequip
    self.fail("Need to Create Test")
AssertionError: Need to Create Test

======================================================================
FAIL: test_details (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/Jevin.Evans/Documents/CODE/Game/FUNCLG/tests/test_armor.py", line 206, in test_details
    self.fail("Need to Create Test")
AssertionError: Need to Create Test

======================================================================
FAIL: test_export (tests.test_armor.ArmorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/Users/Jevin.Evans/Documents/CODE/Game/FUNCLG/tests/test_armor.py", line 225, in test_export
    self.fail("Need to Create Test")
AssertionError: Need to Create Test

----------------------------------------------------------------------
Ran 12 tests in 0.051s

FAILED (failures=3)

---Flake 8----

0
